[package]
name = "fulltext-search-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
serde_json = "1.0"
strip_markdown = "0.2"

[dependencies.xorf]
version = "0.11"
features = ["serde"]

[dependencies.bincode]
version = "1.3"